postgres:
  conn: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}

kafka:
  bootstrap: "localhost:9092"
  producer_client_id: "qa-producer"
  topics:
    personal:  "hr.personal"
    positions: "hr.positions"
    history:   "hr.history"

userAPI:
  port: 8080

